### PAGE SETTINGS


# TITEL (of website)
title: 'Transformation Models'


# SLOGAN(on homepage in <title> and other important places)
slogan: 'Research and Software for Transformation Models'


# DESCRIPTION (max 150 characters, on homepage and in footer for quick description)
description: 'Research and Software for Transformation Models'


# CREDITS (in footer)
credits: '<p>Built with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/" target="_blank">Feeling Responsive</a> by <a href="http://phlow.de/"target="_blank">Phlow</a>.</p>'

# Main author of the website
# See > authors.yml
author: "Torsten Hothorn"


# main address for absolute links
url: "http://ctm.r-forge.r-project.org"
baseurl: ""

urlimg: "http://ctm.r-forge.r-project.org/images/"
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)

# Logo (size 600x80 pixels)
logo: "logo.png"

# Plugins
plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate


### PAGINATION (BLOG: NEWS)
blogurl: "/news/"
paginate: 5                      # Paginates all X entries# 
paginate_path: "/news/page:num"   # Pagination path › Important for blog page in /blog/ to work

markdown           : kramdown #theme works best with this
permalink          : /news/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - 'README.*'
    - '*.bib'
    - pages/Makefile
    - '*.Rmd'


# LANGUAGE SETTING (used in /includes/header.html for html-settings)
language: 'en'


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


# DEFAULT SETTINGS
defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: "Torsten Hothorn"    # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: "Torsten Hothorn"     # Default author for posts


### Navigation: _data/navigation.yml to adjust the left/right topbar navigation


### SEO: Verify Website to Webmaster Tools
google_author:             ""
google_site_verification:  ""


# SASS: More › http://jekyllrb.com/docs/assets/#sassscss
sass:
    sass_dir : _sass
    style    : :compressed

